### PR TITLE
SUP-765, Redirect logged in user to member dashboard

### PR DESCRIPTION
**Pull request by vikasrohit**

### CODE REVIEW

**Comment by vikasrohit** [comment]
@thabofletcher Can you please check if the solution is fine. I am specifically in doubt for the check that I have removed for modal check at line number [113](https://github.com/appirio-tech/tc-site/pull/108/files#diff-8e895045eb1e5d44a2ee4444caaceed6L113)

**Comment by thabofletcher** [comment]
@vikasrohit I believe the removal of line 113 is ok since we want this behavior for both modal and non modal logins. However, the logic of using referer etc is setup for the non-modal login, so I believe if the user ends up at a page with a modal login when the referer was an external URL, they could go back to an external URL.

I think we might want to wait to solidify the redirection logic once we have the new login page that is always non-modal, and handle it using a parameter (like next=) rather than referer, and the behavior will be more predictable.

@ajefts What do you think about doing the my-dashboard redirection after the new login page? Should be much simpler to implement then.

**Comment by vikasrohit** [comment]
Thanks @thabofletcher  for details. I was afraid of this kind of issue so I tried to test out multiple scenarios but didn't test the case you mentioned. For now, if don't want to block the story, I can put specific check rather being in else block for modal popup in line [115](https://github.com/appirio-tech/tc-site/pull/108/files#diff-8e895045eb1e5d44a2ee4444caaceed6R115)

**Comment by vikasrohit** [comment]
Not needed to be merged as changes are done via Nginx rewrites.

**Pull request closed without merging**
