### PR TITLE
[PR for review] API migration [COR-119]

### PR DESCRIPTION
**Pull request by ykohata**
[COR-119 - Migrate existing www user reg to use new Auth Service](https://appirio.atlassian.net/browse/COR-119)

Functionalities modified for this story:
* Login
* Registration
* Registration with social account
* Forgot Password

### CODE REVIEW

**Comment by ykohata** [comment]
@thabofletcher Could you please review this modification?, which partially changes usage of v2 to v3

I created a development instance. It is available at [http://local.topcoder-dev.com/] with the following configuration in your local machine.

/etc/hosts
```
127.0.0.1	localhost local.topcoder-dev.com
```

Port fowarding
```
sudo ssh -i /path/to/topcoder-dev-vpc-nat.pem -l ec2-user 54.164.99.116 -L 80:10.15.50.201:8080
```

Thanks!

FYI: @sudoster

**Comment by thabofletcher** [comment]
Hi @ykohata, sorry I missed this notification. Will this code migrate to the new auth for tc-site, or is this a v2 compatible auth system that will aid in the migration to v3?

**Comment by ykohata** [comment]
@thabofletcher No problem, Thanks.
I changed some v2 API invocations in the tc-site code to v3 API. For this migration, target v3 API is compatible with v2. For example, the login API in v3 now creates tcjwt and tcsso coockies.
 (fyi: @sudoster)

**Comment by thabofletcher** [comment]
Great, thanks @ykohata - so in that case the code looks good to me, if you have tested, we can push to qa for testing and release, if you are ready.

**Pull request closed without merging**
