### PR TITLE
fixed appirio-tech/topcoder-app/issues/1011 added function

### PR DESCRIPTION
**Pull request by shubhendusaurabh**
fixed appirio-tech/topcoder-app/issues/1011 added function for back

### CODE REVIEW

**Comment by birdofpreyru** [comment]
@shubhendusaurabh Hey, I just wonder, have you managed to test this change locally? When I attempt to access submission page in a locally deployed version of the page, it does not open it, but shows me the challenge specs page instead :( Probably, you know some secret?

The change itself looks fine to me, but I still would like to test it, just to double-check.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru I am using vagrant setup, so it might have different setup.
can you check page template for submission page in WordPress admin? Mine is setup to use the angular version.

**Comment by birdofpreyru** [comment]
@shubhendusaurabh I am also using Vagrant setup, and I have not touch anything in WP admin since a while ago. Even don't remember the credentials now (are there some standard admin username/password coming with the Vagrant, or are they something you have choosen when setting everything up?)

**Comment by shubhendusaurabh** [comment]
Username and password both are tcdev. Its on the readme of git repo. :smile:

**Comment by birdofpreyru** [comment]
You know, we have so much different repos, that it is oftern much faster to ask somebody who knows, than to find relative note yourself. Thanks for the credentials, they work, but now I'm having problems to find options for the submission page...

**Comment by birdofpreyru** [comment]
Yeah, I think I found it, but it does not help yet. Gonna dig around to see what is wrong with my setup :/

**Comment by shubhendusaurabh** [comment]
Check rewrite rules for the page. There is a rewrite rules plugin in wordpress admin, activate and check the url for submission page.

**Comment by birdofpreyru** [comment]
Ohh... I don't know, what is wrong with my setup. Rewrite rules look fine, but it looks like not all of them are executed :( Anyway, I was able to confirm that your changes are fine after going to the submission page manually printing its URL in the necessary format, and then seeing that Back button gets me to the right place.

**Pull request merged**
