### PR TITLE
SUP-3097, Display F2F Data science challenges in data science listing

### PR DESCRIPTION
**Pull request by vikasrohit**
Added F2F challengeType filter along with Code

@ajefts @parthshah @deepanprabhu fyi

### CODE REVIEW

**Comment by parthshah** [comment]
:+1: , that was a simple fix :)

**Comment by vikasrohit** [comment]
Yes, indeed. The fix was simple but spinning up tc-site correctly is always a time consuming task and further, after style updates to the challenge listing page 3-4 months back, it stopped loading the page correctly on local.topcoder-dev.com URL and with local.topcoder.com it keeps on reloading itself. :(

**Comment by parthshah** [comment]
Okay, well hopefully we wont have to deal with this for too long. What do you need to get this tested & deployed to prod?

**Comment by vikasrohit** [comment]
I have tested it on dev. So, I think we are good to go. I may try creating a F2F challenge in qa to test it out on qa as well.

**Pull request merged**
